name: Build & Release Electron App

permissions:
  contents: write    # Required for creating releases and uploading assets
  actions: read      # Required for downloading artifacts

on:
  push:
    tags:
      - "v*" # Trigger only on version tags (e.g., v1.0.0)

jobs:
  build:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Rebuild native dependencies
        run: npm run postinstall

      - name: Build
        timeout-minutes: 45
        shell: bash
        env:
          GITHUB_TOKEN: ""  # Disable auto-publish
          GH_TOKEN: ""
          CI: ""
          DEBUG: "electron-builder"
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run build:electron -- --mac --publish=never
          else
            npm run build:electron -- --win --publish=never
          fi

      - name: Verify macOS app signature
        if: matrix.os == 'macos-latest' && env.CODESIGN_IDENTITY != ''
        shell: bash
        run: |
          APP_PATH=$(echo dist/mac*/*.app | head -n 1)
          echo "Verifying codesign for $APP_PATH"
          codesign --verify --deep --strict --verbose=2 "$APP_PATH"
          echo "Verifying Gatekeeper assessment for $APP_PATH"
          spctl --assess --type execute --verbose=4 "$APP_PATH"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: dist/*
          retention-days: 7
          compression-level: 6
        timeout-minutes: 15

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/Variable Tester-Setup-*.dmg
            dist/**/Variable Tester-Setup-*.zip
            dist/**/Variable Tester-Setup-*.exe
            dist/**/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
