name: Build & Release Electron App

permissions:
  contents: write    # Required for creating releases and uploading assets
  actions: read      # Required for downloading artifacts

on:
  push:
    tags:
      - "v*" # Trigger only on version tags (e.g., v1.0.0)

jobs:
  build:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Rebuild native dependencies
        run: npm run postinstall

      - name: Build
        timeout-minutes: 45
        shell: bash
        env:
          GITHUB_TOKEN: ""  # Disable auto-publish
          GH_TOKEN: ""
          CI: ""
          DEBUG: "electron-builder"
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run build:electron -- --mac --${{ matrix.arch }} --publish=never
          else
            npm run build:electron -- --win --${{ matrix.arch }} --publish=never
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}-artifacts
          path: dist/*
          retention-days: 7
          compression-level: 6
        timeout-minutes: 15

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/Variable Tester v2-Setup-*.dmg
            dist/**/Variable Tester v2-Setup-*.exe
            dist/latest.yml
            dist/latest-x64.yml
            dist/latest-arm64.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
